apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: "cassandra-headless"
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        env:
        - name: MAX_HEAP_SIZE
          value: "1024M" # 本地開發極低消耗設定
        - name: HEAP_NEWSIZE
          value: "200M"
        ports:
        - containerPort: 9042
