apiVersion: batch/v1
kind: Job
metadata:
  name: actor-load-generator
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      restartPolicy: Never
      containers:
      - name: client
        image: actor-client:latest
        imagePullPolicy: IfNotPresent
        # 真實內網壓測大砲設定：
        # -tps=100000      : 期望把 2 檯 Node 打到 10 萬 TPS。
        # -concurrency=5000: 模擬 Gateway 挾帶 5 千長連線。
        # -batch=2000      : 將 Envelope 高度壓實，降低網路 I/O Syscall。
        args: ["-etcd=etcd-client:2379", "-tps=100000", "-concurrency=5000", "-batch=2000", "-duration=30s"]
