// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: pkg/remote/proto/actor_cluster.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActorServiceClient is the client API for ActorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActorServiceClient interface {
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (ActorService_StreamMessagesClient, error)
}

type actorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActorServiceClient(cc grpc.ClientConnInterface) ActorServiceClient {
	return &actorServiceClient{cc}
}

func (c *actorServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (ActorService_StreamMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &ActorService_ServiceDesc.Streams[0], "/remote.ActorService/StreamMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &actorServiceStreamMessagesClient{stream}
	return x, nil
}

type ActorService_StreamMessagesClient interface {
	Send(*BatchRequest) error
	Recv() (*BatchResponse, error)
	grpc.ClientStream
}

type actorServiceStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *actorServiceStreamMessagesClient) Send(m *BatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *actorServiceStreamMessagesClient) Recv() (*BatchResponse, error) {
	m := new(BatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ActorServiceServer is the server API for ActorService service.
// All implementations must embed UnimplementedActorServiceServer
// for forward compatibility
type ActorServiceServer interface {
	StreamMessages(ActorService_StreamMessagesServer) error
	mustEmbedUnimplementedActorServiceServer()
}

// UnimplementedActorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedActorServiceServer struct {
}

func (UnimplementedActorServiceServer) StreamMessages(ActorService_StreamMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedActorServiceServer) mustEmbedUnimplementedActorServiceServer() {}

// UnsafeActorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorServiceServer will
// result in compilation errors.
type UnsafeActorServiceServer interface {
	mustEmbedUnimplementedActorServiceServer()
}

func RegisterActorServiceServer(s grpc.ServiceRegistrar, srv ActorServiceServer) {
	s.RegisterService(&ActorService_ServiceDesc, srv)
}

func _ActorService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ActorServiceServer).StreamMessages(&actorServiceStreamMessagesServer{stream})
}

type ActorService_StreamMessagesServer interface {
	Send(*BatchResponse) error
	Recv() (*BatchRequest, error)
	grpc.ServerStream
}

type actorServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *actorServiceStreamMessagesServer) Send(m *BatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *actorServiceStreamMessagesServer) Recv() (*BatchRequest, error) {
	m := new(BatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ActorService_ServiceDesc is the grpc.ServiceDesc for ActorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote.ActorService",
	HandlerType: (*ActorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _ActorService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/remote/proto/actor_cluster.proto",
}
